---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: strapi_cms
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: strapi_cms
        tier: backend
        track: stable
    spec:
      containers:
        - name: strapi_cms
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 1337